### ISSUE TITLE
Training a policy

### ISSUE THREAD

**Issue by Williambert** [zcczhang/UVD#7]
Hi, thanks for this paper. I tested out UVD subtask decomposition on multiple videos and it does really well. I want to compare policy training algorithm as explained in your paper with some other algorithms. How can I initiate policy training using the code from this repository? Despite thoroughly reviewing all the files, I couldn't locate any specific file dedicated to this task. Is the training code not included in this repository, or am I missing something out?

**Comment by zcczhang** [comment]
Hi @Williambert Thanks for the interest! And yes the current codebase does not include the trainer (which I used pytorch lightning), in order to prevent dependency issues with other popular training frameworks --- the motivation for UVD is an off-the-shelf decomposer so our hope is that UVD APIs in this codebase can be directly called in any existing IL or RL codebase. We are also trying to clean up the internal scripts upon the camera-ready release, but at the moment you could just directly use the decomposition script offline before the training and use any or your own policy training codebase :)
